"""
Django settings for xonadon_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'listings',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k3dilttc=hlw2#%xtcwu1^u5kz#!lu%fqh#u46n-#di$i23z8p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']

# Render (and similar PaaS) terminate TLS at a proxy and forward plain HTTP
# to the app, so Django needs to be told the original request was HTTPS -
# otherwise CSRF's Origin check fails for real https:// requests.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS', 'https://xonadon.onrender.com'
    ).split(',') if origin.strip()
]

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_RATES': {
        # Rate-limit admin login attempts per IP to blunt password guessing.
        'admin_login': '5/min',
        # Rate-limit how often one IP can trigger a new Telegram deep
        # link/verification row, to blunt spamming the bot.
        'telegram_start': '10/min',
    },
}

# --- Stripe (listing payments) ---------------------------------------
# Keys live only in env vars - never commit real keys. Until they're set,
# the payment endpoints report "not configured" instead of crashing, so
# the rest of the site keeps working.
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# Price per PAID listing tier, in USD cents, server-side only - the
# client never gets to say what it should pay. 'regular' listings are
# free and are not in this dict at all - posting one skips Stripe
# entirely. Override either value with an env var (e.g.
# PRICE_VIP_CENTS=1600) without a redeploy of code.
LISTING_PRICE_CENTS = {
    'top': int(os.environ.get('PRICE_TOP_CENTS', '280')),           # ~$2.80 (35 000 so'm)
    'vip': int(os.environ.get('PRICE_VIP_CENTS', '800')),           # ~$8.00 (100 000 so'm)
}

# --- Telegram bot (replaces SMS for the signup verification code) ----
# Same "not configured until the env var is set" story as Stripe above.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_BOT_USERNAME = os.environ.get('TELEGRAM_BOT_USERNAME', 'J_joymee_bot')
# Public base URL Telegram needs to reach for the webhook. RENDER_EXTERNAL_URL
# isn't reliably present, so fall back to the known production domain
# (matches CSRF_TRUSTED_ORIGINS above) instead of silently doing nothing.
SITE_BASE_URL = (
    os.environ.get('RENDER_EXTERNAL_URL')
    or os.environ.get('SITE_BASE_URL')
    or 'https://xonadon.onrender.com'
)


# Application definition



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'xonadon_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xonadon_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
CORS_ALLOW_ALL_ORIGINS = True

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'