# Generated by Django 6.1 on 2026-08-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('price', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(default=0)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('type_key', models.CharField(max_length=50)),
                ('repair', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('seller', models.CharField(max_length=100)),
                ('owner_role', models.CharField(default='Uy egasi', max_length=100)),
                ('owner', models.BooleanField(default=True)),
                ('mortgage', models.BooleanField(default=False)),
                ('deal', models.CharField(choices=[('sotuv', 'Sotuv'), ('ijara', 'Ijara'), ('kunlik', 'Kunlik')], default='sotuv', max_length=20)),
                ('vip', models.BooleanField(default=False)),
                ('top', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
    ]
