# Generated by Django 6.1 on 2026-08-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(default='Uy egasi', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
