# Generated by Django 6.1 on 2026-08-21 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingListingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('tier', models.CharField(choices=[('regular', 'Oddiy'), ('top', 'Top'), ('vip', 'Vip')], max_length=20)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('payload', models.JSONField()),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='listings.listing')),
            ],
        ),
    ]
