# Generated by Django 6.1 on 2026-08-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_normalize_existing_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PendingBalanceTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='listings.profile')),
            ],
        ),
    ]
