# Generated by Django 6.1 on 2026-08-22 12:25

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_profile_balance_cents_pendingbalancetopup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=listings.models._new_telegram_token, max_length=40, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('chat_id', models.CharField(blank=True, max_length=40)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
