# Generated by Django 6.1 on 2026-08-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_telegramverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
