# Generated by Django 6.1 on 2026-08-24 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listingimage_rework'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='posted_tier',
            field=models.CharField(choices=[('regular', 'Oddiy'), ('top', 'Top'), ('vip', 'Vip')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='stage_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
