# Generated by Django 6.1 on 2026-08-24 06:07

from django.db import migrations


def backfill(apps, schema_editor):
    Listing = apps.get_model('listings', 'Listing')
    Listing.objects.filter(vip=True).update(posted_tier='vip')
    Listing.objects.filter(vip=False, top=True).update(posted_tier='top')
    Listing.objects.filter(vip=False, top=False).update(posted_tier='regular')


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_posted_tier_listing_stage_started_at'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
