# Generated by Django 6.1 on 2026-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldListingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('tier', models.CharField(default='regular', max_length=20)),
                ('original_listing_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
