# Generated by Django 6.1 on 2026-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_profile_verified_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('ye', 'у.е'), ('usd', 'USD'), ('uzs', "UZS (so'm)")], default='ye', max_length=10),
        ),
    ]
