# Generated by Django 6.1 on 2026-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_voicenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverification',
            name='gateway_request_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
