# Generated by Django 6.1 on 2026-08-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_telegramverification_gateway_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
