# Generated by Django 6.1 on 2026-08-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_profile_email_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_wanted',
            field=models.BooleanField(default=False),
        ),
    ]
