# Generated by Django 6.1 on 2026-08-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_listing_is_wanted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('balance_topup', "Balans to'ldirish"), ('tier_purchase', "E'lon turi (yangi)"), ('tier_upgrade', "Reklama qilish (mavjud e'lon)")], max_length=20)),
                ('tier', models.CharField(blank=True, max_length=20)),
                ('amount_cents', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TierDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('top', 'Top'), ('vip', 'Vip')], max_length=20)),
                ('percent', models.PositiveIntegerField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='listings.profile')),
            ],
        ),
    ]
