# Generated by Django 6.1 on 2026-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_profile_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tg_message_ids',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
