# Generated by Django 6.1 on 2026-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_listing_tg_message_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_code_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
