# Generated by Django 6.1 on 2026-09-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_profile_login_code_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='ig_media_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
