# Generated by Django 6.1 on 2026-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_sitesetting_listing_ig_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
