# Generated by Django 6.1 on 2026-10-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_profile_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
