# Generated by Django 6.1 on 2026-10-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_listing_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=10)),
                ('kind', models.CharField(choices=[('listing', "E'lon / reklama"), ('topup', "Balans to'ldirish")], max_length=10)),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('amount_uzs', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('click_trans_id', models.CharField(blank=True, default='', max_length=64)),
                ('click_paydoc_id', models.CharField(blank=True, default='', max_length=64)),
                ('click_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='listings.pendinglistingpayment')),
                ('pending_topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='listings.pendingbalancetopup')),
            ],
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(max_length=64, unique=True)),
                ('payme_time', models.BigIntegerField()),
                ('amount_tiyin', models.BigIntegerField()),
                ('state', models.IntegerField(default=1)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('create_time', models.BigIntegerField()),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transactions', to='listings.uzpayment')),
            ],
        ),
    ]
